### ISSUE TITLE
audio/waveform.mp3 must be an existed file?

### ISSUE THREAD

**Issue by AsashioB** [ryanheise/just_waveform#13]
If I want to handle an generated file, what should I do?

**Comment by ryanheise** [comment]
Even if you generate a file, it still has a file path, doesn't it?

**Comment by ryanheise** [comment]
You could be right that that is what @AsashioB means (in which case your answer is correct), although to me the question is still not clear. Since @AsashioB hasn't responded, I'll close this issue.
