### ISSUE TITLE
Is it possible to extract audio from Stream?

### ISSUE THREAD

**Issue by MapperMalte** [ryanheise/just_waveform#14]
Hello,

Thanks a lot for your nice plugin. One question: Is it possible to render the waveform for an audio-stream that is being recorded? I use your package just_audio and the package record: ^3.0.3 to do recordings.

Best regards,
MapperMalte

**Comment by ryanheise** [comment]
Such a feature can only be supported directly as a feature of whatever recorder plugin you use. If that plugin doesn't support it, you need to either make a feature request there or search for a different plugin.
