### ISSUE TITLE
Frozen on 99% while generating.

### ISSUE THREAD

**Issue by BlackGold-1989** [ryanheise/just_waveform#23]
I just added that package on my flutter project. Awesome package.
But I met to frozen waveform generate on 99% while creating. 
If anyone has some solutions for that, Please let me know.

=== My flutter doctor ===
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.6-0.0.pre.2, on macOS 12.5.1 21G83 darwin-x64, locale en-LA)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.71.0)
[✓] VS Code (version 1.54.2)
[✓] Connected device (3 available)
    ! Error: JinYZ’s iPhone has recently restarted. Xcode will continue when JinYZ’s iPhone is unlocked. (code -14)
[✓] HTTP Host Availability
```

=== My Test Device ===
Samgsung A20

Thanks.

**Comment by ryanheise** [comment]
Are you reporting for Android or iOS?

**Comment by BlackGold-1989** [comment]
Android -- Samsung A20 --- API 31

**Comment by BlackGold-1989** [comment]
<img width="934" alt="Screen Shot 2022-09-05 at 15 42 11" src="https://user-images.githubusercontent.com/58547693/188407304-19547647-c784-4a1d-9fcd-27c9ed03cbb9.png">
For fixing that, the "invoke method" is not needed any more?

**Comment by elvisgn** [comment]
Hi,
Having the frozen issue on iOS 15.x using 0.0.3 version. Was this fixed?

**Comment by ryanheise** [comment]
#12 has now been merged and published. If you continue to experience the same issue, please reopen it and let me know how I can reproduce it.
