### ISSUE TITLE
Example code load asset error

### ISSUE THREAD

**Issue by alphatero** [ryanheise/just_waveform#25]
Hi, I am first tring flutter develop and just_waveform. 
I tried to run example but it got error message: Unable to load asset: audio/waveform.mp3.
Can help me to know where I got wrong?
![pic](https://user-images.githubusercontent.com/46735230/197378030-37c49254-82e9-431a-b64c-84e55f16cd41.png)

**Comment by ryanheise** [comment]
The asset `audio/waveform.mp3` is right there in the example directory, so I am guessing that you are probably not running the example as is. Am I right?

**Comment by alphatero** [comment]
Hi, thanks for your reply.
This is may project root, I think I have put the mp3 in there, is there wrong?
![root](https://user-images.githubusercontent.com/46735230/197384128-3b28add8-3369-429b-ac40-90395b5ab1c7.png)

**Comment by ryanheise** [comment]
Why should you need to "put" the mp3 there? It is already there in the example. 

May I ask something for clarification? Are you really running the example, or are you running your own project where you have just copied and pasted code? If it's your own project, then please try the actual example to confirm whether it works. That will rule out whether this is a problem with my example or not.

**Comment by alphatero** [comment]
Sorry, you are right.
I tried to run example by fork full plugin project success. 
But why I can't run by copied and pasted code?

**Comment by ryanheise** [comment]
Since there is no issue with the plugin or the example, I'll close this issue.

For your issue, I think it is not with the plugin, but with how you use assets, therefore I suggest you read a little about how to use assets in Flutter.
