### ISSUE TITLE
PlatformException(ExtAudioOpenURL error, ExtAudioOpenURL error, null, null)

### ISSUE THREAD

**Issue by LastMonopoly** [ryanheise/just_waveform#28]
Doesn't work for certain mp3 file, see attachment.
[6607054370125122307.mp3.zip](https://github.com/ryanheise/just_waveform/files/10375543/6607054370125122307.mp3.zip)

**Comment by ryanheise** [comment]
Are you sure that's an mp3 file? On iOS/macOS, file names must have the correct filename extension, and it seems like someone just stamped mp3 on it without checking.

**Comment by ryanheise** [comment]
```
$ file 6607054370125122307.mp3
6607054370125122307.mp3: ISO Media, Apple iTunes ALAC/AAC-LC (.M4A) Audio
```

**Comment by LastMonopoly** [comment]
Got it, thanks!
