### ISSUE TITLE
just_audio integration

### ISSUE THREAD

**Issue by pigivc** [ryanheise/just_waveform#29]
Sorry if it looks like a dumb question, but is there anyway to integrate this with just_audio player? I wanna use it as progress indicator.

**Comment by ryanheise** [comment]
What kind of progress? Download progress, waveform extraction progress, or playback progress?

**Comment by pigivc** [comment]
> What kind of progress? Download progress, waveform extraction progress, or playback progress?

yes, playback progress, of course.

**Comment by ryanheise** [comment]
Then yes, of course.
