### ISSUE TITLE
just_audio waveform design

### ISSUE THREAD

**Issue by ara-chinaryan** [ryanheise/just_waveform#30]
Is it possible to connect this plugin with just_audio I want to make a player with waveform design?  
![seek bar](https://github.com/ryanheise/just_waveform/assets/16429715/328ae83c-4712-47a6-a12e-8eaa180a306d)

**Comment by ryanheise** [comment]
Of course, but as far as just_waveform is concerned, that is up to you. All this plugin needs to do is provide you with the waveform data, and you are free to render it however you want and whenever you want.

If you are new to programming, you can try asking a series of well formed and narrow questions on StackOverflow (or on something like ChatGPT or Bard, although the former has a knowledge cutoff date before the creation of just_waveform).
