### ISSUE TITLE
Just audio wavefrom

### ISSUE THREAD

**Issue by ara-chinaryan** [ryanheise/just_waveform#31]
You took and immediately closed my problem.  And the Internet does not have any information about how to connect these two plugins.  There is no such question on Stackoverflow and ChatGpt doesn't know your plugin.  Can you share the code?  I don't think it's that much of a problem for you.  There is no documentation about it at all.  Yes, I'm new to programming. And how to deal with this issue?  
![Screenshot_2023-07-21-18-51-20-784_fambox pro-edit](https://github.com/ryanheise/just_waveform/assets/16429715/14eae8ad-f8d2-46e2-93b5-74e46fe5f2b6)

**Comment by ryanheise** [comment]
Closing and locking. I tried to help you in your previous issue by pointing you to the correct place to ask questions. GitHub is for reporting issues, and you have not pointed out an actual issue in the plugin that needs to be fixed.

If it was not clear from the previous issue, it is not my job to teach you how to program, and you should not assume how much of a burden you would be placing on me by demanding that I teach you programming by spamming the same question multiple times.

If you decide create a third issue despite my previous reply, I will unfortunately have to block you, so please don't do that and seek programming help in the places you were already advised in your last so-called "issue".
